{
  "name": "next-tailwind-boilerplate",
  "description": "a nextjs and tailwindcss boilerplate by themefisher.com",
  "version": "1.0.5",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "dev": "node lib/jsonGenerator.js && next dev",
    "build": "node lib/jsonGenerator.js && next build",
    "export": "next build && next export",
    "lint": "next lint",
    "start": "next start",
    "test": "npx playwright test"
  },
  "dependencies": {
    "csv-parser": "^3.0.0",
    "date-fns": "^2.29.3",
    "disqus-react": "^1.1.5",
    "dotenv": "^16.0.3",
    "fs": "0.0.1-security",
    "github-slugger": "^2.0.0",
    "glob": "^9.3.2",
    "gray-matter": "^4.0.3",
    "marked": "^4.2.12",
    "next": "13.1.5",
    "next-i18next": "^13.2.2",
    "next-mdx-remote": "^4.3.0",
    "next-themes": "^0.2.1",
    "react": "18.2.0",
    "react-cookie-consent": "^8.0.1",
    "react-dom": "18.2.0",
    "react-gtm-module": "^2.0.11",
    "react-icons": "^4.7.1",
    "react-lite-youtube-embed": "^2.3.52",
    "react-mailchimp-subscribe": "^2.1.3",
    "react-syntax-highlighter": "^15.5.0",
    "rehype-slug": "^5.1.0",
    "remark": "^14.0.2",
    "remark-gfm": "^3.0.1",
    "remark-html": "^15.0.2",
    "remark-react": "^9.0.1"
  },
  "devDependencies": {
    "@playwright/test": "^1.32.3",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "autoprefixer": "^10.4.13",
    "date-fns": "^2.29.3",
    "date-fns-tz": "^1.3.7",
    "eslint": "8.32.0",
    "eslint-config-next": "13.1.5",
    "jshint": "^2.13.6",
    "lighthouse": "^10.1.0",
    "node-fetch": "^3.3.1",
    "playwright": "^1.32.1",
    "playwright-lighthouse": "^3.0.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.3",
    "prettier-plugin-tailwindcss": "^0.2.2",
    "sass": "^1.57.1",
    "sharp": "^0.31.3",
    "tailwind-bootstrap-grid": "^5.0.1",
    "tailwind-scrollbar": "^2.1.0",
    "tailwindcss": "^3.2.4",
    "util": "^0.12.5"
  }
}
